### ISSUE TITLE
v1.0.0 release

### ISSUE THREAD

**Issue by hartzis** [dozoisch/react-google-recaptcha#91]
path to `v1.0.0` - `react-google-recaptcha` has been a solid choice in the react community for [years](https://github.com/dozoisch/react-google-recaptcha/releases) with a solid API

- [x] use `react-async-script@v1.0.0` https://github.com/dozoisch/react-async-script/issues/33
  - [x] create `1.x` branch and test `react-async-script@v1.0.0-rc1` - PR made #94
- [x] add support for the "error-callback" - #93 

Working `1.0.0` release candidate - https://codesandbox.io/s/1y4zzjq37l

**Comment by hartzis** [comment]
@dozoisch You rock! I updated the [codesandbox.io](https://codesandbox.io/s/1y4zzjq37l) example to use `1.0.0`, everything looks great!

Thank you for all your time and effort too! /high-five
